/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ip_project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class DatabaseAndTable extends javax.swing.JFrame {

    /**
     * Creates new form DatabaseAndTable
     */
    
    public static String DATABASENAME = "" ;
    
    public DatabaseAndTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    Statement stmt = null;
    Statement stmt1 = null;
    ResultSet rs = null;
    ResultSet rs1 =null;
    String SQL = "SHOW DATABASES ;";
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        tf1.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        tf1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf1MouseClicked(evt);
            }
        });
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1);
        tf1.setBounds(690, 370, 450, 62);

        jButton1.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jButton1.setText("Drop");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(820, 480, 110, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("D A T A B A S E   O P E R A T I O N S");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(420, 60, 410, 81);

        jButton3.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jButton3.setText("Use");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(950, 480, 70, 40);

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel3.setText("Enter the name of the database ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(690, 250, 165, 22);

        jList1.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jList1.setModel(new DefaultListModel());
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(230, 230, 395, 370);

        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel4.setText("To help you out , here's a list of existing databases :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(230, 190, 420, 22);

        jButton4.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1040, 480, 100, 40);

        jLabel5.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel5.setText("(Or select a database from the list)");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(690, 330, 280, 30);

        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel6.setText("you want to create / drop :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(690, 280, 145, 22);

        jButton2.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jButton2.setText("Create");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(690, 480, 67, 40);

        jButton5.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jButton5.setText("Backup - Restore");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(820, 560, 200, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

//DROPPING A DATABASE        

try {
           
        Class.forName("com.mysql.jdbc.Driver");
        Connection con =
        DriverManager.getConnection("jdbc:mysql://localhost/information_schema","root","12345");
        Statement stmt = null;
        ResultSet rs = null;
        String s = tf1.getText().trim();
            
        stmt = con.createStatement();
           
        int x = stmt.executeUpdate("DROP DATABASE " +(s)+ " ;");
        
    }
       

catch(Exception e ) {
                       JOptionPane.showMessageDialog(null,e.getMessage());
                    }
        
        
JOptionPane.showMessageDialog(null,"You Have Successfully Dropped The Database !!");


       


// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

//DISPLAYING DATABASES                

tf1.requestFocus();
        
tf1.setText("(No Special Characters And No Spaces)");

DefaultListModel dModel = (DefaultListModel) jList1.getModel();
dModel.clear();
        
try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/test","root","12345");
            stmt = con.createStatement();
            rs = stmt.executeQuery(SQL);
            
            while (rs.next()) {
            String a = rs.getString("Database");
            dModel.addElement(a);
             
                               }
            jList1.setModel(dModel);
            con.close();
    } 

catch (Exception e) {
                       JOptionPane.showMessageDialog(this,e.getMessage());
                    }




// TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  
//USING A DATABASE        
        
try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con =
        DriverManager.getConnection("jdbc:mysql://localhost/information_schema","root","12345");
        Statement stmt = null;
        ResultSet rs = null;
        String s = tf1.getText().trim();
            
        stmt = con.createStatement();
            
        int x = stmt.executeUpdate("Use " +(s)+ " ;");    
    }
       

catch(Exception e ){
                       JOptionPane.showMessageDialog(null,e.getMessage());
                   }
        

JOptionPane.showMessageDialog(null,"Database Changed.");




try{
            Class.forName("com.mysql.jdbc.Driver");
             Connection con =
            DriverManager.getConnection("jdbc:mysql://localhost/assorted_DB","root","12345");
             Statement stmt1= null;
             ResultSet rs1=null;

             String s=tf1.getText().trim();
             stmt1=con.createStatement();
             java.util.Date date=new java.util.Date();
			
            java.sql.Date sqlDate=new java.sql.Date(date.getTime());
            java.sql.Timestamp sqlTime=new java.sql.Timestamp(date.getTime());
            PreparedStatement ps=con.prepareStatement("insert into databs (db_name,db_time,db_date,db_id) values(?,?,?,?)");
                          //ResultSet tableKeys = ps.getGeneratedKeys();

          String qury="Select db_id from db_names where database_name like '"+DATABASENAME+"';";
          rs1 = stmt1.executeQuery(qury);
          
          String aaa = "";
          
           while (rs1.next()) {
               aaa = rs1.getString("db_id");            
                               }
          
          
           // ps.setInt(1,0);
            ps.setString(1,DATABASENAME);
            ps.setDate(3,sqlDate);
			ps.setTimestamp(2,sqlTime);
                        ps.setString(4,aaa);
			ps.executeUpdate();			
			
			ps.close();

                  }
        catch(Exception e){
            //JOptionPane.showMessageDialog(null,e.getMessage());
       
        }
              //JOptionPane.showMessageDialog(null,"Database Saved.");
      
        


// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
   
      String b =  (String)jList1.getSelectedValue();
      tf1.setText(b);
                
      DATABASENAME = b;
      HomeScreen.flag = 1;

// TODO add your handling code here:
    }//GEN-LAST:event_jList1MouseClicked

    private void tf1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf1MouseClicked

tf1.setText("");
tf1.setEnabled(true);
tf1.requestFocus();

// TODO add your handling code here:
    }//GEN-LAST:event_tf1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
this.setVisible(false);
new HomeScreen().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//CREATING DATABASES

 try {
           Class.forName("com.mysql.jdbc.Driver");
            Connection con =
            DriverManager.getConnection("jdbc:mysql://localhost/information_schema","root","12345");
            Statement stmt = null;
            ResultSet rs = null;
            String s = tf1.getText().trim();
            
            stmt = con.createStatement();
            
        int x = stmt.executeUpdate("Create Database " +(s)+ " ;");
        


           }
       
       catch(Exception e ){
       JOptionPane.showMessageDialog(null,e.getMessage());
                          }
        
        
        JOptionPane.showMessageDialog(null,"You Have Successfully Created A Database !!");
        
        
        
        try {
           Class.forName("com.mysql.jdbc.Driver");
            Connection con =
            DriverManager.getConnection("jdbc:mysql://localhost/assorted_DB","root","12345");
            Statement stmt2 = null;
            ResultSet rs2 = null;
           String s=tf1.getText().trim();
             stmt1=con.createStatement();
             java.util.Date date=new java.util.Date();
			
            java.sql.Date sqlDate=new java.sql.Date(date.getTime());
            java.sql.Timestamp sqlTime=new java.sql.Timestamp(date.getTime());
            PreparedStatement ps=con.prepareStatement("insert into db_names (database_name) values(?)");
                      //   ResultSet tableKeys = ps.getGeneratedKeys();

         //  tableKeys.next();
 //int autoGeneratedID = tableKeys.getInt(1);
           // ps.setInt(1,0);
        //    ps.setInt(1,autoGeneratedID);
          //  ps.setDate(3,sqlDate);
			ps.setString(1,s);
			ps.executeUpdate();			
			
			ps.close();


           }
       
       catch(Exception e ){
       JOptionPane.showMessageDialog(null,e.getMessage());
                          }
        
        
     
        
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
this.setVisible(false);
new BackupandRestore().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatabaseAndTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatabaseAndTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatabaseAndTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatabaseAndTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatabaseAndTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
}
