/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ip_project;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Navigate extends javax.swing.JFrame {
    
  
    /**
     * Creates new form Navigate
     */
    public Navigate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmdPrev = new javax.swing.JButton();
        cmdLast = new javax.swing.JButton();
        cmdFirst = new javax.swing.JButton();
        cmdNext = new javax.swing.JButton();
        cmdExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Navigate Through Existing Records");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 30, 620, 81);

        t1.setFont(new java.awt.Font("Agency FB", 0, 25)); // NOI18N
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(530, 150, 449, 40);

        t2.setFont(new java.awt.Font("Agency FB", 0, 25)); // NOI18N
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2);
        t2.setBounds(530, 240, 449, 40);

        t3.setFont(new java.awt.Font("Agency FB", 0, 25)); // NOI18N
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        getContentPane().add(t3);
        t3.setBounds(530, 330, 449, 40);

        t4.setFont(new java.awt.Font("Agency FB", 0, 25)); // NOI18N
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        getContentPane().add(t4);
        t4.setBounds(530, 420, 449, 40);

        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel6.setText("Gender :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(310, 520, 84, 40);

        buttonGroup1.add(rb1);
        rb1.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        rb1.setText("MALE");
        getContentPane().add(rb1);
        rb1.setBounds(530, 510, 55, 50);

        buttonGroup1.add(rb2);
        rb2.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        rb2.setText("FEMALE");
        getContentPane().add(rb2);
        rb2.setBounds(660, 510, 65, 50);

        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel2.setText("Employee ID No. :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 150, 89, 22);

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel3.setText("Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 230, 36, 45);

        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel4.setText("City :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 330, 26, 22);

        jLabel5.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel5.setText("Mobile No. :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 420, 58, 45);

        cmdPrev.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        cmdPrev.setText("Previous");
        cmdPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrevActionPerformed(evt);
            }
        });
        getContentPane().add(cmdPrev);
        cmdPrev.setBounds(590, 580, 130, 31);

        cmdLast.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        cmdLast.setText("Last");
        cmdLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLastActionPerformed(evt);
            }
        });
        getContentPane().add(cmdLast);
        cmdLast.setBounds(750, 580, 110, 31);

        cmdFirst.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        cmdFirst.setText("First");
        cmdFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFirstActionPerformed(evt);
            }
        });
        getContentPane().add(cmdFirst);
        cmdFirst.setBounds(310, 580, 110, 31);

        cmdNext.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        cmdNext.setText("Next");
        cmdNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNextActionPerformed(evt);
            }
        });
        getContentPane().add(cmdNext);
        cmdNext.setBounds(450, 580, 110, 31);

        cmdExit.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        cmdExit.setText("Exit");
        cmdExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdExitActionPerformed(evt);
            }
        });
        getContentPane().add(cmdExit);
        cmdExit.setBounds(880, 580, 100, 31);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   Statement stmt = null;
    ResultSet rs = null;
    String SQL = "SELECT * FROM emp";
    public void disable_textfields() {
        t1.setEditable(false);
        t2.setEditable(false);
        t3.setEditable(false);
        t4.setEditable(false);
    }

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed

    }//GEN-LAST:event_t1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed

    }//GEN-LAST:event_t2ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed

    }//GEN-LAST:event_t3ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed

    }//GEN-LAST:event_t4ActionPerformed

    private void cmdPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrevActionPerformed
        try {

            if (rs.previous()) {
                String PN = rs.getString("empid");
                String PName = rs.getString("empname");
                String PAdd = rs.getString("empcity");
                String PPh = rs.getString("empphone");
                String PSex = rs.getString("empsex");
                t1.setText(PN);
                t2.setText(PName);
                t3.setText(PAdd);
                t4.setText(PPh);
                if(PSex.equals("M"))
                rb1.setSelected(true);
                else
                rb2.setSelected(true);
                cmdFirst.setEnabled(true);
                cmdNext.setEnabled(true);
                cmdPrev.setEnabled(true);
                cmdLast.setEnabled(true);
            } else {
                cmdPrev.setEnabled(false);
                JOptionPane.showMessageDialog(this, "You Have Reached The First Record !!", "Dear User",0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_cmdPrevActionPerformed

    private void cmdLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLastActionPerformed
        try {
            if (rs.last()) {
                String PN = rs.getString("empid");
                String PName = rs.getString("empname");
                String PAdd = rs.getString("empcity");
                String PPh = rs.getString("empphone");
                String PSex = rs.getString("empsex");
                
                t1.setText(PN);
                t2.setText(PName);
                t3.setText(PAdd);
                t4.setText(PPh);
                if(PSex.equals("M"))
                rb1.setSelected(true);
                else
                rb2.setSelected(true);
                cmdFirst.setEnabled(true);
                cmdNext.setEnabled(false);
                cmdPrev.setEnabled(true);
                cmdLast.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "You Have Reached The Last Record !!", "Dear User",0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_cmdLastActionPerformed

    private void cmdFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFirstActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root","12345");
            if (rs.first()) {
                String PN = rs.getString("empid");
                String PName = rs.getString("empname");
                String PAdd = rs.getString("empcity");
                String PPh = rs.getString("empphone");
                String PSex = rs.getString("empsex");
                t1.setText(PN);t2.setText(PName);
                t3.setText(PAdd);t4.setText(PPh);
                if(PSex.equals("M"))
                rb1.setSelected(true);
                else
                rb2.setSelected(true);
                cmdFirst.setEnabled(false);cmdNext.setEnabled(true);
                cmdPrev.setEnabled(false);cmdLast.setEnabled(true);
              } else {
                cmdFirst.setEnabled(false);
                cmdNext.setEnabled(false);
                cmdPrev.setEnabled(false);
                cmdLast.setEnabled(false);
                JOptionPane.showMessageDialog(this, "There Is No Record In The Table !!", "Dear User",0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_cmdFirstActionPerformed

    private void cmdNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNextActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root","12345");
            if (rs.next()) {
                String PN = rs.getString("empid");
                String PName = rs.getString("empname");
                String PAdd = rs.getString("empcity");
                String PPh = rs.getString("empphone");
                String PSex = rs.getString("empsex");
               t1.setText(PN);t2.setText(PName);
                t3.setText(PAdd);t4.setText(PPh);
                if(PSex.equals("M"))
                rb1.setSelected(true);
                else
                rb2.setSelected(true);
                cmdFirst.setEnabled(true);
                cmdNext.setEnabled(true);
                cmdPrev.setEnabled(true);
                cmdLast.setEnabled(true);
            } else {
                cmdNext.setEnabled(false);
                JOptionPane.showMessageDialog(this, "You Have Reached The Last Record !!", "Dear User",0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_cmdNextActionPerformed

    private void cmdExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdExitActionPerformed
        this.setVisible(false);
        new emmgmt().setVisible(true);
        
    }//GEN-LAST:event_cmdExitActionPerformed
 
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
disable_textfields();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root","12345");
            stmt = con.createStatement();
            rs = stmt.executeQuery(SQL);
            if (rs.first())
            {   String PN = rs.getString("empid");
                String PName = rs.getString("empname");
                String PAdd = rs.getString("empcity");
                String PPh = rs.getString("empphone");
                String PSex = rs.getString("empsex");
                t1.setText(PN);t2.setText(PName);
                t3.setText(PAdd);t4.setText(PPh);
                 if(PSex.equals("M"))
                   rb1.setSelected(true);
               else
                   rb2.setSelected(true);
                cmdFirst.setEnabled(false);cmdNext.setEnabled(true);
                cmdPrev.setEnabled(false);cmdLast.setEnabled(true);}
            else
            {cmdFirst.setEnabled(false);cmdNext.setEnabled(false);
             cmdPrev.setEnabled(false);cmdLast.setEnabled(false);
                JOptionPane.showMessageDialog(this, "There Are No Records In The Table !!", "Student",0);}
        } catch (Exception e) {JOptionPane.showMessageDialog(this, e.getMessage());}       



// TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Navigate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Navigate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Navigate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Navigate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Navigate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cmdExit;
    private javax.swing.JButton cmdFirst;
    private javax.swing.JButton cmdLast;
    private javax.swing.JButton cmdNext;
    private javax.swing.JButton cmdPrev;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    // End of variables declaration//GEN-END:variables
}
